replica: 1
image:
  repo: anandnevase/encrypt-decrypt-app
  tag: latest
healthcheck: 
  url: /api/health
name: encrpt-decrypt-app
containerPort: 5000
service:
  name: encrpt-decrypt-app
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30000
